describe("Util", function()
    describe("table", function()
        describe("pack", function()
            it("works", function()
                local a, b, c = 1, 2, 3
                local packed = table.pack(a, b, c)
                assert.are.same({ a, b, c }, packed)
            end)
        end)
    end)
end)
