describe("Util", function()
    describe("math", function()
        describe("round", function()
            it("rounds floats", function()
                assert.are.equal(1, math.round(0.5))
                assert.are.equal(0, math.round(0.499))
            end)

            it("rounds ints", --[[lol]] function()
                assert.are.equal(1, math.round(1))
                assert.are.equal(0, math.round(0))
            end)
        end)
    end)
end)
